import type { Metadata } from "next";
import "./globals.css";
import ReduxProvider from "@/Contexts/ReduxProvider/ReduxProvider";
import Navbar from "@/app/components/Navbar/Navbar";

import { League_Spartan } from "next/font/google";
import MUIContextProvider from "@/Contexts/MUIContext/MUIContext";
import AuthProvider from "@/Contexts/Auth/AuthProvider";

const inter = League_Spartan({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <AuthProvider>
            <MUIContextProvider>
              <Navbar />
              {children}
            </MUIContextProvider>
          </AuthProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
