import type { Metadata } from "next";
import "./globals.css";
import ReduxProvider from "@/app/components/ReduxProvider/ReduxProvider";

import { League_Spartan } from "next/font/google";

const inter = League_Spartan({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          {/*<Navbar />*/}
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
